services:
  # Proxy
  reverseproxy:
    image: nginx:latest
    container_name: reverseproxy
    depends_on:
        - noderedopigpio
        - portainer
        - webcamsrv
        - rpimonitor
        - oalprws
    volumes:
      - ./ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
      - ./ReverseProxy/headers.conf:/etc/nginx/headers.conf
    ports:
      - 80:80
    restart: always

  # noderedopigpio
  noderedopigpio:
    image: noderedopigpio:latest
    container_name: noderedopigpio
    volumes:
      - ./noderedopigpiodata:/data
      - /sys/class/gpio:/sys/class/gpio
    ports:
      - 1880:1880
    restart: always

  # portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainerdata:/data
    ports:
      - 9000:9000
    restart: always

  # webcamsrv
  webcamsrv:
    image: webcamsrv:latest
    container_name: webcamsrv
    ports:
      - "8088:8088"
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      CAMERA_INDEX: "0"
      CAMERA_WIDTH: "1280"
      CAMERA_HEIGHT: "720"
    restart: always
    
  # rpimonitor (https://github.com/michaelmiklis/docker-rpi-monitor)
  rpimonitor:
    image: michaelmiklis/rpi-monitor:latest
    container_name: rpimonitor
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
    restart: always
    ports:
      - 8888:8888

  # oalprws
  # http://oalprws:8080/v1/identify/plate
  # method POST, parametr: image (binary image to recognition)
  oalprws:
    image: dimaby/oalprws:latest
    container_name: oalprws
    ports:
      - "8080:8080"
    restart: always