# Use the official Python image as a base
FROM python:3.8-slim

# Install the necessary system libraries
RUN apt-get update && \
    apt-get install -y libopencv-dev libsm6 libxext6 libxrender-dev tini && \
    rm -rf /var/lib/apt/lists/*

# Install OpenCV Python
RUN pip install opencv-python-headless

# Install the Tornado library
RUN pip install tornado

# Environment variables
ENV CAMERA_RTSP_URL=""
ENV CAMERA_INDEX=0
ENV CAMERA_WIDTH=640
ENV CAMERA_HEIGHT=480

# Copy script to the container
COPY webcamsrv.py /app/webcamsrv.py

# Open port 8888
EXPOSE 8888

# Set the working directory
WORKDIR /app

# Start the server when the container starts via tini for better signal processing
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["python", "webcamsrv.py"]