FROM python:3.8-slim

# Install the necessary system libraries and OpenCV Python
RUN apt-get update && \
    apt-get install -y libopencv-dev libsm6 libxext6 libxrender-dev tini && \
    pip install --no-cache-dir opencv-python-headless tornado && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Environment variables
ENV CAMERA_RTSP_URL=""
ENV CAMERA_INDEX=0
ENV CAMERA_WIDTH=640
ENV CAMERA_HEIGHT=480

# Copy script to the container
COPY webcamsrv.py /app/webcamsrv.py
COPY models /app/models

# Open port 8088
EXPOSE 8088

# Set the working directory
WORKDIR /app

# Start the server when the container starts via tini for better signal processing
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["python", "webcamsrv.py"]
